############################
## CHANGE THESE
############################

baseURL: 'https://sebviolet.github.io/blog2'
title: blog2

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


